// This code runs on Netlify's servers during the build

const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require('fs');

// Get the API key you set in the Netlify UI
const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  throw new Error("GEMINI_API_KEY environment variable not set!");
}

const genAI = new GoogleGenerativeAI(apiKey);

async function createWebsite() {
  console.log("Starting content generation with Gemini...");
  
  const model = genAI.getGenerativeModel({ model: "gemini-pro" });
  
  // --- EDIT YOUR PROMPT HERE! ---
  const prompt = "Write a short, funny, and welcoming paragraph for the homepage of my new personal website.";

  const result = await model.generateContent(prompt);
  const text = result.response.text();

  console.log("Content generated successfully.");

  // This is the HTML structure of your page
  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>My AI-Generated Site</title>
      <style>
        body { font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
      </style>
    </head>
    <body>
      <h1>Welcome to My Site!</h1>
      <p>${text}</p>
      <hr>
      <p><em>This content was generated by Google Gemini during the site build.</em></p>
    </body>
    </html>
  `;

  // Create a folder named 'public' and save the index.html file inside it
  if (!fs.existsSync('public')){
    fs.mkdirSync('public');
  }
  fs.writeFileSync('public/index.html', htmlContent);

  console.log("Site built! 'public/index.html' is ready to be deployed.");
}

createWebsite();
